
#include "exception.h"

#include "cpu.h"
#include "interrupts/gic.h"
#include "kstdio.h"
#include "timer.h"
#include "uart.h"
#include "util/assert.h"

uint64_t Exception::exception_level() {
  uint64_t el;
  asm("mrs %0, CurrentEL" : "=r" (el));
  el = el >> 2 & 0b11;

  return el;
}

void Exception::mask_irqs() {
  asm volatile("msr DAIFSet, #0b0010" ::: "memory");
}

void Exception::unmask_irqs() {
  asm volatile("msr DAIFClr, #0b0010" ::: "memory");
}

// The ExceptionFrame contains the saved/dumped contents of the registers when
// the exception was thrown.
struct ExceptionFrame {
  uint64_t x0;
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  uint64_t x13;
  uint64_t x14;
  uint64_t x15;
  uint64_t x16;
  uint64_t x17;
  uint64_t x18;
  uint64_t x29;
  uint64_t x30;
  uint64_t xzr;

  void print_frame() {
    kprintf("Register dump:\n");
    kprintf("  x0:  %p\n", x0);
    kprintf("  x1:  %p\n", x1);
    kprintf("  x2:  %p\n", x2);
    kprintf("  x3:  %p\n", x3);
    kprintf("  x4:  %p\n", x4);
    kprintf("  x5:  %p\n", x5);
    kprintf("  x6:  %p\n", x6);
    kprintf("  x7:  %p\n", x7);
    kprintf("  x8:  %p\n", x8);
    kprintf("  x9:  %p\n", x9);
    kprintf("  x10: %p\n", x10);
    kprintf("  x11: %p\n", x11);
    kprintf("  x12: %p\n", x12);
    kprintf("  x13: %p\n", x13);
    kprintf("  x14: %p\n", x14);
    kprintf("  x15: %p\n", x15);
    kprintf("  x16: %p\n", x16);
    kprintf("  x17: %p\n", x17);
    kprintf("  x18: %p\n", x18);
    kprintf("  x29: %p\n", x29);
    kprintf("  x30: %p\n", x30);
    kprintf("  xzr: %p\n", xzr);
  }
};

static const uint32_t ESR_EL1_EC_SHIFT = 26;
static const uint32_t ESR_EL1_EC_BITS = 0b111111;

static const uint64_t EC_UDF_INS = 0;

// Data Abort exception taken without a change in Exception level.
// Used for MMU and MPU faults generated by instruction accesses and synchronous
// External aborts, including synchronous parity or ECC errors. Not used for
// debug-related exceptions
static const uint64_t EC_DATA_ABRT = 37; // 0b100101;

extern "C" bool Exception::exception_handler(ExceptionFrame* frame_ptr) {
  uint64_t exception_syndrome = 0;
  asm ("mrs %0, ESR_EL1" : "=r" (exception_syndrome));

  uint64_t exception_link = 0;
  asm ("mrs %0, ELR_EL1" : "=r" (exception_link));

  // The exception class holds what kind of exception has occurred
  const uint64_t exception_class = (exception_syndrome >> ESR_EL1_EC_SHIFT) & ESR_EL1_EC_BITS;

  const bool bad_ec = exception_class == EC_UDF_INS ||
                      exception_class == EC_DATA_ABRT;

  kprintf("\nGot an exception (from %p)\n", exception_link);
  kprintf("- The EC is: %d\n", exception_class);

  frame_ptr->print_frame();

  return bad_ec;
}

extern "C" uint32_t Exception::irq_handler(uint32_t intid, ExceptionFrame* frame_ptr) {
  (void)frame_ptr;
  //kprintf("IRQ INTID %d handled by %d\n", intid, CPU::id());

  kprecond(GIC::driver()->version() == GIC::DriverVersion::v2 || (intid != 1022 && intid != 1023));

  if (intid == 30) {
    kprintf("[%z] Generic Timer Interrupt (INTID %d)\n", CPU::id(), intid);
    Timer::set_timer();
  } else if (intid == UART::intid()) {
    // The UART hardware has sent an interrupt signaling that there is input available to read from ...
    // The UART hardware has sent an interrupt signaling that there is room available to send character to ...
    UART::pl011_handle_irq();
  } else {
    kprintf("[%z] Unhandled interrupt with INTID: %d\n", CPU::id(), intid);
  }

  return intid;
}
