
#include "exception.h"
#include "kstdio.h"
#include "timer.h"
#include "uart.h"

uint64_t Exception::get_exception_level() {
  uint64_t el;
  asm("mrs %0, CurrentEL" : "=r" (el));
  el = el >> 2 & 0b11;

  return el;
}

uint64_t Exception::get_cpuid() {
  uint64_t mpidr;
  asm volatile(
   "mrs   %0, MPIDR_EL1   \n\t\
    and   %0, %0, #0xff   \n\t\
    "
    : "=r"(mpidr) :: "memory"
  );

  return mpidr;
}

void Exception::mask_interrupts() {
  asm volatile("msr DAIFSet, #0b0010" ::: "memory");
}

void Exception::unmask_interrupts() {
  asm volatile("msr DAIFClr, #0b0010" ::: "memory");
}

// The ExceptionFrame contains the saved/dumped contents of the registers when
// the exception was thrown.
struct ExceptionFrame {
  uint64_t x0;
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  uint64_t x13;
  uint64_t x14;
  uint64_t x15;
  uint64_t x16;
  uint64_t x17;
  uint64_t x18;
  uint64_t x29;
  uint64_t x30;
  uint64_t xzr;

  void print_frame() {
    kprintf("Register dump:\n");
    kprintf("  x0:  %p\n", x0);
    kprintf("  x1:  %p\n", x1);
    kprintf("  x2:  %p\n", x2);
    kprintf("  x3:  %p\n", x3);
    kprintf("  x4:  %p\n", x4);
    kprintf("  x5:  %p\n", x5);
    kprintf("  x6:  %p\n", x6);
    kprintf("  x7:  %p\n", x7);
    kprintf("  x8:  %p\n", x8);
    kprintf("  x9:  %p\n", x9);
    kprintf("  x10: %p\n", x10);
    kprintf("  x11: %p\n", x11);
    kprintf("  x12: %p\n", x12);
    kprintf("  x13: %p\n", x13);
    kprintf("  x14: %p\n", x14);
    kprintf("  x15: %p\n", x15);
    kprintf("  x16: %p\n", x16);
    kprintf("  x17: %p\n", x17);
    kprintf("  x18: %p\n", x18);
    kprintf("  x29: %p\n", x29);
    kprintf("  x30: %p\n", x30);
    kprintf("  xzr: %p\n", xzr);
  }
};

static const uint32_t ESR_EL1_EC_SHIFT = 26;

static const uint64_t EC_UDF_INS = 0;

// Data Abort exception taken without a change in Exception level.
// Used for MMU and MPU faults generated by instruction accesses and synchronous
// External aborts, including synchronous parity or ECC errors. Not used for
// debug-related exceptions
static const uint64_t EC_DATA_ABRT = 37; // 0b100101;

extern "C" bool Exception::exception_handler(ExceptionFrame* frame_ptr) {
  uint64_t exception_syndrome = 0;
  asm ("mrs %0, ESR_EL1" : "=r" (exception_syndrome));

  uint64_t exception_link = 0;
  asm ("mrs %0, ELR_EL1" : "=r" (exception_link));

  // bits [31, 26] represent the "exception class", i.e., what kind of exception
  // has occurred.
  const uint64_t exception_class = (exception_syndrome >> ESR_EL1_EC_SHIFT) & 0b111111;

  const bool bad_ec = exception_class == EC_UDF_INS ||
                      exception_class == EC_DATA_ABRT;

  kprintf("\nGot an exception (from %p)\n", exception_link);
  kprintf("- The EC is: %d\n", exception_class);

  frame_ptr->print_frame();

  return bad_ec;
}

static UART::ReceiveBuffer uart_rx_irq_buffer;

extern "C" uint32_t Exception::irq_handler(ExceptionFrame* frame_ptr, uint32_t intid) {
  (void)frame_ptr;
  kprintf("IRQ INTID %d handled by %d\n", intid, get_cpuid());

  if (intid == 30) {
    kprintf("Generic Timer Interrupt (INTID %d)\n", intid);
    Timer::set_timer();
  } else if (intid == 33) {
    char c = UART::pl011_recv_async();
    uart_rx_irq_buffer.buffer_char(c);
    kprintf("Buffering char %d (INTID %d)\n", c, intid);
    uart_rx_irq_buffer.print_buffer();
  } else {
    kprintf("Unhandled interrupt with INTID: %d\n", intid);
  }

  return intid;
}
